### ISSUE TITLE
Create constants for all magic strings

### ISSUE THREAD

**Issue by Bartmax** [DotNetAnalyzers/Proposals#30] opened 2014-11-24 14:14 UTC
I want to suggest a feature for roslyn that shouldn't be hard to implement. 

as the title suggest. 

Imagine the following code :

```
public void Something() {
    db.Where(c=> c.Color == "yellow");
}
```

after doing Create constants for all magic strings code will be like this :

```
private const readonly string YELLOW = "yellow";
public void Something() {
    db.Where(c=> c.Color == YELLOW);
}
```

there are edge cases but you get the point.

**Comment by sharwell** [comment] 2014-11-24 14:21
A remarkably accurate duplicate of #28. :smile:

**Closed as completed by sharwell** 2014-11-24 14:21 UTC
Labels: duplicate

**Comment by Bartmax** [comment] 2014-11-24 14:25
yes I proposed there and they suggested to put it here :) didn't see someone else did. so yes, it's the same
