### ISSUE TITLE
Class name does not match file name

### ISSUE THREAD

**Issue by ilmax** [DotNetAnalyzers/Proposals#38] opened 2015-01-18 18:56 UTC
I always keep the file name coherent with the class name, but some refactorings can break this. I would like to have such fix available. The only thing to figure out is the naming of generic types. Somebody use the class name with no generic at all, some (like EF for example) append the ` in the file name (note that the arity is not included).

**Comment by sharwell** [comment] 2015-01-18 21:10
You aren't the only one :smile: 

Duplicate of #13

**Closed as completed by sharwell** 2015-01-18 21:10 UTC
Labels: duplicate
